{% set name = "mlxtend" %}
{% set version = "0.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rasbt/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7ae3abec411f51dff732d2281733db2a19e4d134292503a4f3a875939065b2b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # Package requires numpy>=2.3.5, but this version is not available for py310
  # https://github.com/numpy/numpy/blob/v2.3.5/pyproject.toml#L19
  skip: true  # [py<311]

requirements:
  host:
    - pip
    - python
    - setuptools >=59.0.0
  run:
    - python
    - joblib >=1.5.2
    - matplotlib-base >=3.10.8
    - numpy >=2.3.5
    - pandas >=2.3.3
    - scikit-learn >=1.8.0
    - scipy >=1.16.3

test:
  source_files:
    - mlxtend/_base/tests
  imports:
    - mlxtend
    - mlxtend._base
    - mlxtend.classifier
    - mlxtend.cluster
    - mlxtend.data
    - mlxtend.evaluate
    - mlxtend.externals
    - mlxtend.feature_extraction
    - mlxtend.feature_selection
    - mlxtend.file_io
    - mlxtend.frequent_patterns
    - mlxtend.math
    - mlxtend.plotting
    - mlxtend.preprocessing
    - mlxtend.regressor
    - mlxtend.text
    - mlxtend.utils
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v mlxtend/_base/tests

about:
  home: https://github.com/rasbt/mlxtend
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE-BSD3.txt
  summary: Machine Learning Library Extensions
  description: |
    A library of Python tools and extensions for data science and machine learning.
  doc_url: https://rasbt.github.io/mlxtend
  dev_url: https://github.com/rasbt/mlxtend

extra:
  recipe-maintainers:
    - rasbt
