{% set name = "mlxtend" %}
{% set version = "0.15.0.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "f59cadf199563fdaa0bfeff2327de4dc49571c22f92140ed0e5e1135723aded9" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dlib >=19.17.0
    - numpy >=1.14.6
    - scipy >=1.1.0
    - scikit-learn >=0.20.1
    - pandas >=0.23.4
    - matplotlib >=1.5.1

test:
  requires:
    - nose
  imports:
    - mlxtend
    - mlxtend._base
    - mlxtend.classifier
    - mlxtend.cluster
    - mlxtend.data
    - mlxtend.evaluate
    - mlxtend.externals
    - mlxtend.feature_extraction
    - mlxtend.feature_selection
    - mlxtend.file_io
    - mlxtend.frequent_patterns
    - mlxtend.image
    - mlxtend.math
    - mlxtend.plotting
    - mlxtend.preprocessing
    - mlxtend.regressor
    - mlxtend.text
    - mlxtend.utils

about:
  home: https://github.com/rasbt/mlxtend
  license: BSD v3
  license_family: BSD
  license_file: LICENSE-BSD3.txt
  summary: Machine Learning Library Extensions
  description: >
    A library of Python tools and extensions for data science
    and machine learning.

    Contact
    =============

    If you have any questions or comments about mlxtend,
    please feel free to contact me via
    eMail: mail@sebastianraschka.com
    or Twitter: https://twitter.com/rasbt

    This project is hosted at https://github.com/rasbt/mlxtend
    The documentation can be found at http://rasbt.github.io/mlxtend/
  doc_url: 'http://rasbt.github.io/mlxtend/'
  dev_url: 'https://github.com/rasbt/mlxtend'

extra:
  recipe-maintainers:
    - rasbt
