{% set name = "mlxtend" %}
{% set version = "0.23.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba8c8427cbe65d462c8487511331cae0cdcf9252d92f8687f0a53d311128770f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - joblib >=0.13.2
    - matplotlib-base >=3.0.0
    - numpy >=1.16.2
    - pandas >=0.24.2
    - scikit-learn >=1.3.1
    - scipy >=1.2.1

test:
  imports:
    - mlxtend
    - mlxtend._base
    - mlxtend.classifier
    - mlxtend.cluster
    - mlxtend.data
    - mlxtend.evaluate
    - mlxtend.externals
    - mlxtend.feature_extraction
    - mlxtend.feature_selection
    - mlxtend.file_io
    - mlxtend.frequent_patterns
    - mlxtend.math
    - mlxtend.plotting
    - mlxtend.preprocessing
    - mlxtend.regressor
    - mlxtend.text
    - mlxtend.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rasbt/mlxtend
  license: BSD-3-Clause
  license_family: BSD
  license_file: |
    - LICENSE-BSD3.txt
    - LICENSE-CC-BY.txt
  summary: Machine Learning Library Extensions
  description: |
    A library of Python tools and extensions for data science and machine learning.
  doc_url: https://rasbt.github.io/mlxtend/
  dev_url: https://github.com/rasbt/mlxtend

extra:
  recipe-maintainers:
    - rasbt
