travis:
  secure:
    BINSTAR_TOKEN: fRPQUmN7b7xnu2OUS6wPkxplb+DsbR6gdbv22sE9GPCFRSuU3bw5/Jomx1RRekFQEgxeD+3E82t5vtyjUn/Z32LunS52RYzJRgqS88WzZPJOMdYrONFjfD1qsux9c7pKkjiVRgabvLKVcgr1Q/50tyKz6YYivfu7nTT//bYj+QSEe8YKozMKKsH13TRGykoeD9i1oV5T+ZghTfTh0rfbOjN2nO+xhN2/E/t8JAggtFMEbpE9NSYGgnpWshx2h7DR61JpnM0exXqsw/LtUant3PIwwaqSMjTPLSFehxbi0HuTPr4ZIluLDoeOdn04D/GY+nhg3l7FY264zqH6ZDY3+xkKveDOjnYEql5JNFBG5TRDXXnmSThD68NEOmGf9zPSDixmOSkLB6+S6j5cFCmxwNZYChs02ilFTFCAxWkpOEmGsAxzJUzEN48MGbB2vM0/PzMZrro8hvJ3uP+qQH5tLTKPHv98m/LWfkW9Xl6ZnsFQFo2Miqwl680eQOA7AeQ5G/AUC0mKft3PPmIoynz3tXbxJdOF1dYVE9RCbv7DmHBCvpgL0P+OBwRE9v7nyzR1+hA8RXCvPy9zDtRoQdo/Y59CaVzDawewi6F5ypxcapftiCTmL62zHMH/B3JdOrJBy9mX9Di1d+xF1ouhHzCfuD9PPXeOave61sfV3XJyIkA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
