travis:
  secure:
    BINSTAR_TOKEN: cQ+3IZmhGNubt2PDHQJ6HsG9iGP0T+L2y1gh5gUwI8S3dtgeYqKgk8kM1dBiw/v1nrHdQsPcEWxhDalJe5P0453dulWTJtww4fgR5CuL8R0lrfvF+Kr9QP6WsYWxl6iT4KBxgMqz4aH9AdL1xASgr/wLnkc+SBiaAZCm2Kw9D1YF+MMx5DZ6ddFEp30cU86ncWEahACwnGB76yqPDSxKx3UOTjHegh9kMg67X+AyBNdol/CaY5RXouc6UL0A/RxWRj9RdFwf5IFUD3duJl1JvyC0PYlw12Vodt9Q0KccBU4jZCCkI16XoDdgaAy74S6IGdF5/a5cJuqZTy9yPrjIpydgLR7Etbvx1ADBdA/Iq5maIZ+7PghgkAnCs3uK5irDcFfDao0Mfy+4tLLY9lXtZYwQ7xENmcN+VptqwsbiJ7GekDcQ/aECAPThKZ00DlnD8ZXwE0ulflyds8/HlHPkimw/gYi47yRO1zzCBMXMI8lpMmU4w9rQyNWG5Wa2G/d/LAcxFnpOdLZ2F97mJT2mg4I0EcYzE5IbnNx8b3b9vpwNMBiiT1+Hb/jQvtIDvqCzYk432f7c68Qe1ODgiujrTsORd3nbq6uwR5RVxt60DWKH5VkKr6n4K8IT4ze0FvtyhhKpfIy4bgbtS22LL6HmGC8sM8UIZLIqB4ehzYM3AuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
