travis:
  secure:
    BINSTAR_TOKEN: KQKs+Tv3UIJix37/bvWGvoMypSOTPrqy0Bo0G2Z0Fs0uHPioT/GftyrDLBvd7B/lE02ynhHI23naRKr1yVT3MimKrgWqfQJGLUkNwCVQnklElV1oaGpbtKy8qD8ULrLrV+PYdjfEjDjT6VU92TAvfo98BikfenucY3Mm0fE/hI538rOhFDFZVoH+8P8c1rE+0ZWDe5YV6XT4vsJE5Ko98iDSBUP0beni3e+Tpr5CxXj/aYCc6E2V7+7ZsuyAnFc6jyfEq6g1VCuv6Cv746Q86Vj6YsOY3J/LbLwcMyTrTHUHnTJ1oBlJuNskiwrevLe2XBTzcpx/3TaOIUD/oZYEpsLunhu6P8E35cPEeCh53HNALO4hh30GklftoZw+5kGrYeX3IWZTe3ywiVs155uT7pyHA+vTgLQJpZR/ZbGOwgrW/E8s03fmC5ui5jJLo7JcZkB24aGsiidgZivmcrkQHpW12yfnvMD/5wC3onR8a0aZI4KCAsTtjq3LHX7G0Hu56xl2NkzNMht82v7RPd5HV8vIuj4bnE/rY36PLgIPOoP++PX55fDyHnvCDxZLb+21hDPlIWEgEXcz/mS6lzmLqUbyqG2LPFcwF550zp/YlP2g2Ns9v6+uCqWh0NF+ItljjDURu1hVCQgoa4QwJItGvxHD3/cENoRCel35NC9vYLI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
