travis:
  secure:
    BINSTAR_TOKEN: otPOo2+a2m0hPkyGktunIVP58oZcHNbyVgevmCgU6+h/q8iZx5LD+afxLK4kq/dtBfVSpxer73e2SboYudm0cIKKxZxRnzzaAPRrY3kYVc/aP37XpTVaj2+dFMLCh1MPb2Ig3UrhDrlngjqSwbY5MnOTrpCfNW38/Ov722kQAsDSPOwVpEut8c189B30woi9nUmpoPobZ4dnkWR6Yf4B0ddamPixJfPL3/qMKxJotmVZCNbsGABihUd1bkWLrXOyuL32BFppXaKs4mBYOLXg2PJ9/9GhaJlDPCSwdJ9J0J+WO8DZiV7wEl99/zEh7mb/xxAYyXxbxnHH9T6GcGF12M0oSIuoritMR8eDisMEHykRb6ooq7ZwECgRjfApeNIqIvzckRfyesrI+uFjkoClAjGIUG4OsMW+U0eozFKeBkty/LIu3x/gts1cE6RD4qc/TXIavZiGe2HqGH6cXX3it/srPaoRiX+hklm5B1GOS1SC9EbxY6uM8vTxO27MVJ4cDKbYZwfPlMoNAUYd2uT96QtBPk7OFyIcvjUHWvEuCdvAtkjJID2aDMHb4gWd5ohwn4San4ADncV+IkADyV7jgKDHTahHpTyPujoY75Do2qO7R3JKvWmTLc+Ziftg3AAuUlJxfnSpHg3pcl9xpsCP18aTH/DUSmU9vj+RW/WokAk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
